# Generated by Django 2.1.7 on 2019-04-08 07:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=40, verbose_name='链接名字')),
                ('urls_link', models.CharField(max_length=120, verbose_name='链接地址')),
                ('index', models.SmallIntegerField(default=0, verbose_name='权重值')),
                ('desc', models.CharField(max_length=120, verbose_name='简单描述')),
                ('note', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
