# Generated by Django 2.1.7 on 2019-04-09 01:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190408_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('p', models.CharField(max_length=40, verbose_name='链接名字')),
                ('index', models.SmallIntegerField(default=0, verbose_name='权重值')),
                ('desc', models.CharField(blank=True, max_length=120, null=True, verbose_name='简单描述')),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'blog_aboutinfo',
            },
        ),
        migrations.CreateModel(
            name='AboutProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=40, verbose_name='项目名字')),
                ('urls_link', models.CharField(max_length=120, verbose_name='项目地址')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('index', models.SmallIntegerField(default=0, verbose_name='权重值')),
                ('desc', models.CharField(blank=True, max_length=120, null=True, verbose_name='项目描述')),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'blog_aboutproject',
            },
        ),
        migrations.CreateModel(
            name='AboutWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('company', models.CharField(max_length=40, verbose_name='公司')),
                ('urls_link', models.CharField(max_length=120, verbose_name='公司地址')),
                ('index', models.SmallIntegerField(default=0, verbose_name='权重值')),
                ('job', models.CharField(blank=True, max_length=120, null=True, verbose_name='岗位')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'blog_aboutwork',
            },
        ),
        migrations.AlterField(
            model_name='links',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterModelTable(
            name='links',
            table='blog_links',
        ),
    ]
