# Generated by Django 2.1.7 on 2019-04-04 04:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('comment', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=100)),
                ('body', tinymce.models.HTMLField(blank=True, verbose_name='博文')),
            ],
            options={
                'db_table': 'blog_article',
            },
        ),
    ]
