# Generated by Django 2.1.7 on 2019-04-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190408_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='abstract_non',
            field=models.TextField(blank=True),
        ),
    ]
